FROM node:18-alpine3.18

# WORKDIR /app

# COPY ./package*.json ./

# RUN npm install

# COPY ./ ./

# EXPOSE 3000

# CMD [ "npm", "run", "dev" ]

WORKDIR /usr/src/next

COPY *.* /usr/src/next

RUN npm install

COPY . /usr/src/next

RUN npm run build

CMD [ "npm" , "run" , "dev"]