FROM node:18-alpine3.18

# WORKDIR /app

# COPY ./package*.json ./

# RUN npm install

# COPY ./ ./

# EXPOSE 3000

# CMD [ "npm", "run", "dev" ]

WORKDIR /app

COPY *.* /app

RUN npm install

COPY . /app

RUN npm run build

CMD [ "npm" , "run" , "dev"]