version: "3"
services:
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: social_frontend_product

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    container_name: social_nginx_product
    ports:
      - "3000:80"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: social_backend
    restart: always
    env_file:
      - ./.env
    environment:
      DB_TYPE: $DB_TYPE
      DB_HOST: $DB_HOST
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_PORT: $DB_PORT
      DB_SYNCHRONIZE: $DB_SYNCHRONIZE
      MAIL_HOST: $MAIL_HOST
      MAIL_PORT: $MAIL_PORT
      MAIL_USER: $MAIL_USER
      MAIL_PWD: $MAIL_PWD
      JWT_ACCESS_TOKEN_SECRET: $JWT_ACCESS_TOKEN_SECRET
      JWT_ACCESS_TOKEN_EXPIRATION: $JWT_ACCESS_TOKEN_EXPIRATION
      JWT_REFRESH_TOKEN_SECRET: $JWT_REFRESH_TOKEN_SECRET
      JWT_REFRESH_TOKEN_EXPIRATION: $JWT_REFRESH_TOKEN_EXPIRATION
      COOKIE_MAX_AGE: $COOKIE_MAX_AGE
      ACCESS_TOKEN_COOKIE_NAME: $ACCESS_TOKEN_COOKIE_NAME
      REFRESH_TOKEN_COOKIE_NAME: $REFRESH_TOKEN_COOKIE_NAME
      SECRET_COOKIE_KEY: $SECRET_COOKIE_KEY
      COOKIE_SECURE: $COOKIE_SECURE
      AWS_BUCKET_REGION: $AWS_BUCKET_REGION
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_BUCKET_NAME: $AWS_BUCKET_NAME
      TOUR_API_SERVICE_KEY: $TOUR_API_SERVICE_KEY
      TOUR_API_END_POINT: $TOUR_API_END_POINT
      THROTTLER_TTL: $THROTTLER_TTL
      THROTTLER_LIMIT: $THROTTLER_LIMIT
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_SECRET: $GOOGLE_SECRET
      GOOGLE_CALLBACK_URL: $GOOGLE_CALLBACK_URL
      NAVER_CLIENT_ID: $NAVER_CLIENT_ID
      NAVER_SECRET: $NAVER_SECRET
      NAVER_CALLBACK_URL: $NAVER_CALLBACK_URL
      KAKAO_CLIENT_ID: $KAKAO_CLIENT_ID
      KAKAO_SECRET: $KAKAO_SECRET
      KAKAO_CALLBACK_URL: $KAKAO_CALLBACK_URL
      APPLICATION_PORT: $APPLICATION_PORT
      GLOBAL_PREFIX: $GLOBAL_PREFIX
      SERVER_PROTOCOL: $SERVER_PROTOCOL
      SERVER_HOST: $SERVER_HOST
      SENTRY_DNS_KEY: $SENTRY_DNS_KEY
      SLACK_URL: $SLACK_URL
      CLIENT_SOCKET_URL: $CLIENT_SOCKET_URL
      REDIS_PROTOCOL: $REDIS_PROTOCOL
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_TYPE: $REDIS_TYPE
