version: "3"
services:
  frontend:
    image: yanggwangseong/social-frontend:latest
    environment:
      NEXT_PUBLIC_COOKIE_KEY: $NEXT_PUBLIC_COOKIE_KEY

  nginx:
    restart: always
    image: yanggwangseong/social-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  backend:
    image: yanggwangseong/social-backend:latest
    environment:
      DB_TYPE: $DB_TYPE
      DB_HOST: $DB_HOST
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_PORT: $DB_PORT
      MAIL_HOST: $MAIL_HOST
      MAIL_PORT: $MAIL_PORT
      MAIL_USER: $MAIL_USER
      MAIL_PWD: $MAIL_PWD
      JWT_ACCESS_TOKEN_SECRET: $JWT_ACCESS_TOKEN_SECRET
      JWT_ACCESS_TOKEN_EXPIRATION: $JWT_ACCESS_TOKEN_EXPIRATION
      JWT_REFRESH_TOKEN_SECRET: $JWT_REFRESH_TOKEN_SECRET
      JWT_REFRESH_TOKEN_EXPIRATION: $JWT_REFRESH_TOKEN_EXPIRATION
      COOKIE_MAX_AGE: $COOKIE_MAX_AGE
      ACCESS_TOKEN_COOKIE_NAME: $ACCESS_TOKEN_COOKIE_NAME
      REFRESH_TOKEN_COOKIE_NAME: $REFRESH_TOKEN_COOKIE_NAME
