version: "3"
services:
  frontend:
    restart: "on-failure"
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      # hot reload를 위해 mount
      - "./frontend:/app"
      - "/app/node_modules"
      # - "/app"
      # - "/app/.next"
    networks:
      - social_network

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    networks:
      - social_network

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: social_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    env_file:
      - ./.env
    environment:
      POSTGRESQL_ROOT_PASSWORD: ${POSTGRESQL_ROOT_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT}
    networks:
      - social_network

  redis:
    image: "redis:alpine"
    container_name: social_redis
    ports:
      - "6379:6379"
    networks:
      - social_network

networks:
  social_network:
