version: "3"
services:
  frontend:
    image: yanggwangseong/social-frontend:latest

  nginx:
    restart: always
    image: yanggwangseong/social-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  backend:
    image: yanggwangseong/social-backend:latest
    environment:
      DB_TYPE: $DB_TYPE
      DB_HOST: $DB_HOST
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_PORT: $DB_PORT
